### PR TITLE
fix: update dom-accessibility-api

### LINKED ISSUE #747: getByRole can't find button by name if title is ""
- `@testing-library/dom` version: 7.22.2
- Testing Framework and version: Jest (whatever version comes with CodeSandbox)
  
- DOM Environment: whatever version comes with CodeSandbox
  

### Relevant code or config:

```js
import React from "react";

export default function App() {
  return <button title="">OK</button>;
}
```

### What you did:

```js
screen.getByRole("button", { name: /ok/i });
```

### What happened:

```text
Unable to find an accessible element with the role "button" and name `/ok/i`

Here are the accessible roles:

  button:

  Name "":
  <button
    title=""
  />
```

### Reproduction:

https://codesandbox.io/s/happy-chandrasekhar-311qt?file=/src/App.js

### Problem description:

Chrome reports that the button has a name:

image

But `getByRole` says it does not.

JSFiddle: https://jsfiddle.net/91retmv2/

### PR DESCRIPTION
**Pull request by marcosvega91**
fix #747 

**What**: This PR will update dom-accessibility-api to the latest version

**Why**: Because in the new version there is a fix for the issue.

The update will solve a problem where title should be ignored when is empty while using name option

**How**: 

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [X] Tests
- [ ] Typescript definitions updated
- [X] Ready to be merged

### CODE REVIEW

File: src/__tests__/role.js [hunk 1]
```diff
@@ -543,3 +543,10 @@ describe('configuration', () => {
     }
   })
 })
+
+test('should get button using his text content when title is empty', () => {
```
Comment (eps1lon) [inline src/__tests__/role.js:547]: I wouldn't add these tests. There's certainly an argument to be made that the dependency is an implementation detail but the point of dependencies is also to cover certain functionality. Otherwise why not copy the whole test suite from dom-accessibility-api?

Comment (marcosvega91) [reply src/__tests__/role.js:547]: Yes you're right, is a duplicate 👍

**Review by eps1lon — APPROVED** [review]
