### PR TITLE
fix: Guard against `jest.useRealTimers` not existing

### LINKED ISSUE #905: jest.useRealTimers() is not a function when running RTL tests in jest-electron environment
I decided to try using `jest-electron` environment in our jest test setup because `jsdom` environment has some missing browser functionality that we were using.

-    "@testing-library/jest-dom": "^5.11.9",
-   "@testing-library/react": "^11.2.3",
-    "@testing-library/user-event": "^12.6.3",
- `node` version: v15.10
- `npm` version: v7

### Relevant code or config:
pasting only necessary changes here of my `jest.config.js` 
```js
{
 .
 .
  runner: 'jest-electron/runner',
  testEnvironment: 'jest-electron/environment',
  .
  .
  .
}
```

### What you did:

ran `npm run test`

### What happened:

i think helpers file inside RTL /dom is calling jest.useFakeTimers()..
which is not available in jest-electron environment.

The error that i'm getting is shown in the following SS.
Screenshot 2021-02-27 at 1 16 00 PM

### Reproduction:
Small repro can be created on local machine on following these steps.
clone : https://github.com/tmtsoftware/esw-ocs-eng-ui
`git checkout jest-branch`
`npm i & npm t`

### Problem description:

RTL/jest-dom helpers are calling jest.timers functionality without checking jest-environment.

### Suggested solution:

there could be some kind of check related to which environment jest is currently running before this line.
` @Testing-Library/dom/dist/helpers.js:38 `.

### PR DESCRIPTION
**Pull request by ph-fritsche**
**What**:

Check if `jest.useRealTimers` is a function before calling it.
Closes #905 

**Why**:

In some environments (e.g. codesandbox) `jest` exists but is either `null` or the `useRealTimers` and `useFakeTimers` don't exist.

**Checklist**:

- N/A Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- N/A Tests
- N/A Typescript definitions updated
- [x] Ready to be merged

### CODE REVIEW

File: src/helpers.js [hunk 1]
```diff
@@ -5,13 +5,18 @@ const TEXT_NODE = 3
...
+    ? runWithJestRealTimers(callback).callbackReturnValue
+    : // istanbul ignore next
+      callback()
+}
 
-  // istanbul ignore next
-  return callback()
+function hasJestTimers() {
+  return (
+    jest !== undefined &&
```
Comment (eps1lon) [inline src/helpers.js:16]:
```suggestion
    typeof jest !== 'undefined' &&
```
To guard against `ReferenceError`

**Review by eps1lon — CHANGES_REQUESTED** [review]
Looks good. Just one potential ReferenceError slipped through I think.

**Review by eps1lon — APPROVED** [review]
Verified this change actually fixes https://github.com/testing-library/dom-testing-library/issues/905 with 

```diff
diff --git a/package.json b/package.json
index 76ba73e..8ab24e3 100644
--- a/package.json
+++ b/package.json
@@ -5,7 +5,7 @@
   "license": "Apache License, Version 2.0",
   "type": "module",
   "dependencies": {
-    "@tmtsoftware/esw-ts": "git+https://github.com/tmtsoftware/esw-ts#2a03d094a7439b4f21bd262c10f13d9f2ef76033",
+    "@tmtsoftware/esw-ts": "https://github.com/eps1lon/esw-ts#fad5e14e22ab4e6019bf8a1012906044ec36aa7e",
     "antd": "^4.13.1",
     "react": "^17.0.1",
     "react-dom": "^17.0.1",
@@ -66,5 +66,8 @@
     "stylelint-config-standard": "^21.0.0",
     "ts-mockito": "^2.6.1",
     "typescript": "^4.2.3"
+  },
+  "resolutions": {
+    "**/@testing-library/dom": "https://pkg.csb.dev/testing-library/dom-testing-library/commit/80a6af82/@testing-library/dom"
   }
 }
```
